{% set version = "7.59.0" %}

package:
  name: curl
  version: {{ version }}

source:
  url: http://curl.haxx.se/download/curl-{{ version }}.tar.bz2
  sha256: b5920ffd6a8c95585fb95070e0ced38322790cb335c39d0dab852d12e157b5a0

build:
  number: 2
  skip: True  # [win and py36]
  detect_binary_files_with_prefix: True

requirements:
  build:
    - perl  # [unix]
    - pkg-config  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    # python is a build requirement on Windows to resolve features.
    # perl is required to run the tests on nix*.
    - krb5
    - libssh2
    - openssl        # [unix]
    - zlib
  run:
    - krb5
    - libssh2
    - openssl          # [unix]
    - zlib

test:
  commands:
    - curl --version
    - curl-config --features  # [not win]
    - curl-config --protocols  # [not win]
    - curl https://raw.githubusercontent.com/conda-forge/curl-feedstock/master/LICENSE
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]
    - nm $PREFIX/lib/libcurl$SHLIB_EXT | grep libssh2_scp_recv2  # [linux]
    - ldd $PREFIX/lib/libcurl.so  # [linux]

about:
  home: http://curl.haxx.se/
  license: MIT/X derivate (http://curl.haxx.se/docs/copyright.html)
  license_family: MIT
  license_file: COPYING
  summary: tool and library for transferring data with URL syntax

extra:
  recipe-maintainers:
    - msarahan
    - jakirkham
    - ocefpaf
